oac-start-services() {
  launchctl load -w -F /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
}

oac-stop-services() {
  launchctl unload /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
}

oac-dump-db() {
  pg_dump -Fc --no-acl --no-owner -h localhost -U oac oac_development > oac_development.dump
}

oac-restore-db() {
  pg_restore --verbose --clean --no-acl --no-owner -h localhost -U oac -d oac_development $1
}
