# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8884d75bb0274896e73ee2467d21d49973f647187218907d79b01916fccc256cfb3540f9079b5044839d247368a45dafd6f07306b586b2f3be71aac81dd9a51e

test:
  secret_key_base: 4c3d44380436ab1134a25b0ce3e473af789f9ee35ab46ce7e65b7b8376c3b9d84b7d1730119e1fabd8bd60e022fc36430c8da1a57038254349d6d4d2c45d02f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
